// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmhtmdsH6fHJgNCRXGNyGIQpeO2p0JOFo',
    appId: '1:589875531317:android:b103d7296feb3062622b7c',
    messagingSenderId: '589875531317',
    projectId: 'score456-58827',
    storageBucket: 'score456-58827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpsKw9xO8wqzEv28cV40KFxhOVT8T636U',
    appId: '1:589875531317:ios:13188d995dd598e7622b7c',
    messagingSenderId: '589875531317',
    projectId: 'score456-58827',
    storageBucket: 'score456-58827.firebasestorage.app',
    iosBundleId: 'com.example.quickscore45',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpsKw9xO8wqzEv28cV40KFxhOVT8T636U',
    appId: '1:589875531317:ios:13188d995dd598e7622b7c',
    messagingSenderId: '589875531317',
    projectId: 'score456-58827',
    storageBucket: 'score456-58827.firebasestorage.app',
    iosBundleId: 'com.example.quickscore45',
  );
}
